### ISSUE TITLE
No way of specifying full table name when tiling

### ISSUE THREAD

**Issue by nkronenfeld** [unchartedsoftware/aperture-tiles#106]
Tiling always appends the field names to the passed-in id.

Perhaps instead, we might want to do a pattern-replacement model, where fields from each piece are substituted into standard patterns in the passed-in id, instead of merely appended to it.

**Comment by cdbethune** [comment]
I'm moving the priority up on this one because it has been a friction point for quite a while.  At minimum  we need to support specifying a tile set name, and have it not be decorated in any way by the tiling process when the resulting set is written out to file, hbase, etc.

**Comment by nkronenfeld** [comment]
Chris, how about just making the specified name have pattern substitution, say {i0} for the name of the x variable, {i1} for the name of the y variable, {v} for the name of the value column?

**Comment by nkronenfeld** [comment]
So if the base property file had:

    com.oculusinfo.index.field0=time
    com.oculusinfo.index.field1=cost
    com.oculusinfo.value.field=utility

then with

    com.oculusinfo.name=cost-v-utility

the table name would just be `cost-v-utility`

but with

    com.oculusinfo.name=cost-v-utility.{i}.{v}

the table name would be the traditional `cost-v-utility.time.cost.utility'

or

    com.oculusinfo.name=graph_{v}.v.{i0}

the table name would be `graph_utility.v.cost

Mostly, this just involves TilingTask.getName, probably index and value name substitution should be done directly by the index and value extractors, rather than having the tiling task have to understand what they do.
