### ISSUE TITLE
Renderer Rework

### ISSUE THREAD

**Issue by nkronenfeld** [unchartedsoftware/aperture-tiles#120]
Our server-side renderers have never gotten any real thought as to the proper way of doing things.

There are a number of cases coming out now that show the inadequacy of our current approach:
- We assume one-tailed data - but much of our potential data is two-tailed
- There are issues with 0 vs unspecified bins - how do we want to draw them (transparent or filled? And can we even tell them apart? Displaying invalid vs. valid but small values.
- Interaction with transformers and color ramps is unclear, unspecified, and inconsistent.
- There's a lot of potential in renderers that will require some more interaction with users - movable zero points, etc.

All this bears a good bit of discussion.

The intent of this issue is to capture that discussion, and hopefully resolve on an ideal implementation which is designed rather than defaulted, as the present implementation is.

Related to #119, #117, #113, #90

**Comment by robharper** [comment]
Smaller issue, but the filter capability in the renderers should be moved into the transformers. Most likely it makes sense to make transformers chainable and make the filter/renormalize step last. That way the renderer just takes a raw value, passes through a transformer and renders it.

Transformers could also be connected to color palettes to complete the loop such that an input raw data value yields an output transformed color.
