### ISSUE TITLE
GraphRecordParser class is missing

### ISSUE THREAD

**Issue by dgiesbrecht** [unchartedsoftware/aperture-tiles#194]
Support for several key components of Graph Tiling appear to be missing in the current code (e.g., oculus.binning.graph.edges.type, oculus.binning.graph.edges.type.index fields, etc.).  

These, and other Graph Tiling parameters, used to be handled in the com.oculusinfo.tilegen.datasets.GraphRecordParser class, which appears to have been removed.

**Comment by cdbethune** [comment]
Any chance all of the refactoring done in support of tiling tasks caused this to be removed?

**Comment by nkronenfeld** [comment]
I'm not finding anything by that name.
Among other things:
git log --all -- '**/GraphRecordParser.scala' shows nothing.
Is there somewhere in the code that refers to it to help track it down?

**Comment by dgiesbrecht** [comment]
It used to be in com.oculusinfo.tilegen.datasets.GraphRecordParser
Specifically in RecordParser.scala

**Comment by nkronenfeld** [comment]
ah, not a file, just a class.  Ok, I'll take a further look

**Comment by nkronenfeld** [comment]
This was removed in the move from CSV to SchemaRDD/DataFrame-based tiling.  It's probably better replaced with a filter pipeline op now.
