### ISSUE TITLE
Bucketed tile generation resulting in n-1 bin dimensions rather than n.

### ISSUE THREAD

**Issue by kbirk** [unchartedsoftware/aperture-tiles#227]
All bucketed tiles seem to contain n-1 x/y bins rather than the correct n.

This bug was been masked by a pixel indexing discrepancy in the NumberListHeatMapImageRenderer vs NumberImageRenderer.  Rather than ensuring each bin is rendered to the correct pixel, the NumberListHeatMapImageRenderer class was interpolating the n-1 bins across the n pixels of the image. 

Overlaying a bucketed heatmap layer over a non-bucketed heatmap layer with a coarseness of 3+ will make the discrepancy between the pixel boundaries apparent.

**Comment by cdbethune** [comment]
@sylvainJE - I had assigned this to you because we originally thought this was a bug in the core tiling code, but it looks like it was a problem with the scripts used to generate the tiles @kbirk was using to test.  No fix needed, although tiles will need to be generated.

**Comment by cdbethune** [comment]
@kbirk - the server must be making assumptions about the size of the tiles being pegged to 256x256.  Is that correct?

**Comment by kbirk** [comment]
@cdbethune - Yes, it uses the OUTPUT_WIDTH and OUTPUT_HEIGHT ConfigurableProperties. Both default to 256.

**Comment by cdbethune** [comment]
@kbirk I'll add a warning log to the server to flag mismatches between the received tile size and the expected tile size.  There are no plans to support mixed tile sizes, so we won't do anything else with it.
