### ISSUE TITLE
Example apps don't work with Tomcat

### ISSUE THREAD

**Issue by robharper** [unchartedsoftware/aperture-tiles#233]
[These lines](https://github.com/unchartedsoftware/aperture-tiles/blob/develop/tile-examples/julia-demo-live/src/main/webapp/WEB-INF/web.xml#L8-L17) are jetty-specific and prevent the WARs from running in Tomcat.

```
	<!-- stop windows from memory mapping the files, which locks them -->
	<servlet>
	    <servlet-name>default</servlet-name>
	    <servlet-class>org.mortbay.jetty.servlet.DefaultServlet</servlet-class>
	    <init-param>
	      	<param-name>useFileMappedBuffer</param-name>
	      	<param-value>false</param-value>
	    </init-param>
	    <load-on-startup>0</load-on-startup>
  	</servlet>
```

**Comment by cdbethune** [comment]
The default override should only be needed when working with Jetty 6 and Gradle for development under Windows, and shouldn't be applied to the example distribution.
