### ISSUE TITLE
compile problems

### ISSUE THREAD

**Issue by sorflex** [unchartedsoftware/aperture-tiles#317]
I'm having an compiling issue with both aperture-tiles and aperturejs:
For aperturejs I get this error:
main:
[INFO] Executed tasks
[INFO] ------------------------------------------------------------------------
[INFO] Building Aperture Server Core Components
[INFO]    task-segment: [compile]
[INFO] ------------------------------------------------------------------------
[INFO] [buildnumber:create {execution: default}]
[INFO] Storing buildNumber: 2016-02-10 19:26:18 at timestamp: 1455132378720
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: null:ehcache-web:jar:null

Reason: Cannot find parent: net.sf.ehcache:ehcache-web-parent for project: null:
ehcache-web:jar:null for project null:ehcache-web:jar:null

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6 seconds
[INFO] Finished at: Wed Feb 10 19:26:18 UTC 2016
[INFO] Final Memory: 31M/74M
[INFO] ------------------------------------------------------------------------
vagrant@tilebox:~/aperture-tiles/aperturejs$

For aperture-tiles I get this:

* What went wrong:
Could not resolve all dependencies for configuration ':tile-service:compile'.
> Could not resolve oculus.aperture:aperture-server-core:develop.
  Required by:
      com.oculusinfo:tile-service:0.6-SNAPSHOT-cdh4.6.0
   > Could not resolve oculus.aperture:aperture-server-core:develop.
      > Could not get resource 'http://maven.oculus.local:8080/archiva/repositor
y/snapshots/oculus/aperture/aperture-server-core/develop/aperture-server-core-de
velop.pom'.
         > Could not GET 'http://maven.oculus.local:8080/archiva/repository/snap
shots/oculus/aperture/aperture-server-core/develop/aperture-server-core-develop.
pom'.
            > maven.oculus.local
   > Could not resolve oculus.aperture:aperture-server-core:develop.
      > Could not get resource 'http://maven.oculus.local:8080/archiva/repositor
y/internal/oculus/aperture/aperture-server-core/develop/aperture-server-core-dev
elop.pom'.
         > Could not GET 'http://maven.oculus.local:8080/archiva/repository/inte
rnal/oculus/aperture/aperture-server-core/develop/aperture-server-core-develop.p
om'.
            > maven.oculus.local
> Could not resolve oculus.aperture.service:aperture-cms:develop.
  Required by:
      com.oculusinfo:tile-service:0.6-SNAPSHOT-cdh4.6.0
   > Could not resolve oculus.aperture.service:aperture-cms:develop.
      > Could not get resource 'http://maven.oculus.local:8080/archiva/repositor
y/snapshots/oculus/aperture/service/aperture-cms/develop/aperture-cms-develop.po
m'.
         > Could not GET 'http://maven.oculus.local:8080/archiva/repository/snap
shots/oculus/aperture/service/aperture-cms/develop/aperture-cms-develop.pom'.
            > maven.oculus.local
   > Could not resolve oculus.aperture.service:aperture-cms:develop.
      > Could not get resource 'http://maven.oculus.local:8080/archiva/repositor
y/internal/oculus/aperture/service/aperture-cms/develop/aperture-cms-develop.pom
'.
         > Could not GET 'http://maven.oculus.local:8080/archiva/repository/inte
rnal/oculus/aperture/service/aperture-cms/develop/aperture-cms-develop.pom'.
            > maven.oculus.local
> Could not resolve oculus.aperture.service:aperture-capture-phantom:develop.
  Required by:
      com.oculusinfo:tile-service:0.6-SNAPSHOT-cdh4.6.0
   > Could not resolve oculus.aperture.service:aperture-capture-phantom:develop.

      > Could not get resource 'http://maven.oculus.local:8080/archiva/repositor
y/snapshots/oculus/aperture/service/aperture-capture-phantom/develop/aperture-ca
pture-phantom-develop.pom'.
         > Could not GET 'http://maven.oculus.local:8080/archiva/repository/snap
shots/oculus/aperture/service/aperture-capture-phantom/develop/aperture-capture-
phantom-develop.pom'.
            > maven.oculus.local
   > Could not resolve oculus.aperture.service:aperture-capture-phantom:develop.

      > Could not get resource 'http://maven.oculus.local:8080/archiva/repositor
y/internal/oculus/aperture/service/aperture-capture-phantom/develop/aperture-cap
ture-phantom-develop.pom'.
         > Could not GET 'http://maven.oculus.local:8080/archiva/repository/inte
rnal/oculus/aperture/service/aperture-capture-phantom/develop/aperture-capture-p
hantom-develop.pom'.
            > maven.oculus.local

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 2 mins 0.569 secs
vagrant@tilebox:~/aperture-tiles$

**Comment by cdbethune** [comment]
We have re-implemented the tiling functionality in a simpler and more flexible library called Salt (http://unchartedsoftware.github.io/salt/).  It has complete documentation, and some simple examples to get started with.  It will be under active development moving forward, so I would suggest taking a look there rather than working with Aperture Tiles.  Sparkpipe (http://unchartedsoftware.github.io/sparkpipe-core/) is worth checking out as well, as it provides a pipeline and some useful primitives for transforming data prior to the tiling process.

**Comment by cdbethune** [comment]
I wasn't able to reproduce the errors you list above, but we did verify everything was compiling again in both Tiles and JS after the fixes we made to address unchartedsoftware/aperturejs#22.  Given that you seem to have had a recent success with compilation process, can I close this?

**Comment by sorflex** [comment]
Yes, you can close this.  Thanks for your help.

Tom
