### ISSUE TITLE
debugging issues

### ISSUE THREAD

**Issue by sorflex** [unchartedsoftware/aperture-tiles#319]
I'm having trouble getting other than a blank screen to display on an aperture-tiles server.  Every compiles and all the tests pass but when I try and run the demos I get a blank window from the web server.  I can select the x and y rulers and move them around and the other buttons but nothing shows up on the main window.  I'm pretty sure its a configuration issue with the demo data but I'm having difficulty debugging it.  Is there any logging?  How do you turn on logging/debugging?

**Comment by cdbethune** [comment]
This doesn't look like a config problem on your end.  I pulled the most recent version on master and there are definitely some issues that are breaking the Julia demo.  I'll have to take a deeper look to determine whether its purely a problem on the client side, or an issue with the tile generation step.

**Comment by sorflex** [comment]
Thanks for looking into this!


Get Outlook for Mobile






On Fri, May 6, 2016 at 1:56 PM -0700, "Chris Bethune" <notifications@github.com> wrote:





This doesn't look like a config problem on your end.  I pulled the most recent version on master and there are definitely some issues that are breaking the Julia demo.  I'll have to take a deeper look to determine whether its purely a problem on the client side, or an issue with the tile generation step.

---

**Comment by cdbethune** [comment]
There was an issue with the bounds set in the demo that would have resulted in the actual tile data not being visible.  That fix, along with some changes to address build errors, are available on the master branch as v0.6.1.  Try that out and let me know if you still have the same problem.

**Comment by cdbethune** [comment]
Assuming v0.6.1 / v7.0 adequately address this issue.
